"""Add HistorialActualizacionRenta model and relation to Contrato

Revision ID: eada4bee0d61
Revises: 5ae3834dc0d7
Create Date: 2025-06-02 23:41:19.340950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eada4bee0d61'
down_revision = '5ae3834dc0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_actualizacion_renta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=False),
    sa.Column('renta_anterior', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('renta_nueva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_actualizacion', sa.String(length=50), nullable=True),
    sa.Column('indice_nombre', sa.String(length=10), nullable=True),
    sa.Column('indice_mes', sa.Integer(), nullable=True),
    sa.Column('indice_ano', sa.Integer(), nullable=True),
    sa.Column('indice_porcentaje', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('importe_fijo_aplicado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descripcion_adicional', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_actualizacion_renta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_actualizacion_renta_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_actualizacion_renta_factura_id'), ['factura_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_actualizacion_renta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_actualizacion_renta_factura_id'))
        batch_op.drop_index(batch_op.f('ix_historial_actualizacion_renta_contrato_id'))

    op.drop_table('historial_actualizacion_renta')
    # ### end Alembic commands ###
